name = "PDDL"
uuid = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
authors = ["Xuan <tanqazx@gmail.com>"]
version = "0.1.1"

[deps]
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"

[compat]
Julog = "0.1.5"
ParserCombinator = "2.0.0"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
