name = "PDDL"
uuid = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
authors = ["Xuan <tanqazx@gmail.com>"]
version = "0.2.15"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"
ValSplit = "0625e100-946b-11ec-09cd-6328dd093154"

[compat]
AutoHashEquals = "0.2, 1.0, 2"
DocStringExtensions = "0.8, 0.9"
IntervalArithmetic = "0.17, 0.18, 0.19, 0.20, 0.21"
Julog = "0.1.15"
ParserCombinator = "2.0.0"
ValSplit = "0.1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
